#!/usr/bin/env python3
import argparse
from pathlib import Path

Q = 8380417
N = 256
ZETA = 1753
OUT = Path(__file__).resolve().parents[1] / "src/zetas.inc"


def bitrev8(x):
    return int(f"{x:08b}"[::-1], 2)


def table():
    assert (Q - 1) % (2 * N) == 0
    assert pow(ZETA, N, Q) == Q - 1
    assert pow(ZETA, 2 * N, Q) == 1

    points = [pow(ZETA, 2 * bitrev8(i) + 1, Q) for i in range(N)]
    assert len(set(points)) == N
    assert all(pow(x, N, Q) == Q - 1 for x in points)

    z = [0] + [pow(ZETA, bitrev8(i), Q) for i in range(1, N)]
    assert all((z[i] * z[i]) % Q == pow(ZETA, 2 * bitrev8(i), Q)
               for i in range(1, N))

    a = [0, 1] + [0] * (N - 2)
    k = 0
    for length in (128, 64, 32, 16, 8, 4, 2, 1):
        for off in range(0, N, 2 * length):
            k += 1
            for j in range(off, off + length):
                t = z[k] * a[j + length] % Q
                a[j], a[j + length] = (a[j] + t) % Q, (a[j] - t) % Q
    assert k == N - 1
    assert a == points
    return z


def render(z):
    lines = ["// generated by tools/gen_zetas.py"]
    for i in range(0, N, 8):
        lines.append("    " + ", ".join(f"{x}U" for x in z[i:i + 8]) + ",")
    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    s = render(table())
    if args.check:
        if OUT.read_text() != s:
            raise SystemExit("twiddle table differs from generator output")
        print("twiddle table verified")
    else:
        OUT.write_text(s)
        print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
