#!/usr/bin/env python3
import argparse
import hashlib
import json
from array import array
from pathlib import Path

from ntt_network import H, N, Q, ZETA, bitrev8, layers, propagation, pullback
from ntt_network import transpose, verify_network

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/prior_tables.inc"
CERT = ROOT / "docs/prior_certificate.json"


def construct(v, a):
    first = [sum(a[j] * c for j, c in row.items()) % Q for row in v]
    assert all(first)
    rows = [{j: c * pow(first[r], -1, Q) % Q for j, c in row.items()}
            for r, row in enumerate(v)]
    cols = [[] for _ in range(N)]
    for r, row in enumerate(rows):
        for j, c in row.items():
            cols[j].append((r, c))
    groups = [(array('H'), array('H'), array('I')) for _ in range(N)]
    for r, x in enumerate(rows):
        for s in range(r):
            y = rows[s]
            j = min(next(iter(x)), next(iter(y)))
            c = (x.get(j, 0) - y.get(j, 0)) % Q
            if not c:
                for j in sorted(x.keys() | y.keys()):
                    c = (x.get(j, 0) - y.get(j, 0)) % Q
                    if c:
                        break
                assert c, (r, s)
            group = groups[j]
            group[0].append(r)
            group[1].append(s)
            group[2].append(pow(c, -1, Q))
    alpha, part, sizes = [0] * N, [0] * len(rows), [0] * N
    for j in reversed(range(N)):
        banned = set()
        for r, s, inv in zip(*groups[j]):
            banned.add((part[s] - part[r]) * inv % Q)
        for r, c in cols[j]:
            if next(iter(rows[r])) == j:
                banned.add(-part[r] * pow(c, -1, Q) % Q)
        x = 1 if j >= N // 2 else 0
        if j >= N // 2:
            assert x not in banned, j
        else:
            while x in banned:
                x += 1
            assert x < Q
        alpha[j] = x
        sizes[j] = len(banned)
        for r, c in cols[j]:
            part[r] = (part[r] + c * x) % Q
        if j in (127, 64, 32, 16, 8, 4, 2, 1, 0):
            print(f"coordinate {j}: forbidden {len(banned)} chosen {x}", flush=True)
    assert all(part)
    assert len(set(part)) == len(rows)
    return alpha, sizes


def render(name, a):
    out = [f"static const uint32_t {name}[{len(a)}] = {{"]
    for i in range(0, len(a), 8):
        out.append("    " + ", ".join(f"{x}U" for x in a[i:i + 8]) + ",")
    return "\n".join(out + ["};"])


def generate():
    assert Q > (2 * N - 1) * N * (H + 1)
    points = [pow(ZETA, 2 * i + 1, Q) for i in range(N)]
    a = [2 * pow(N, -1, Q) * pow(1 - pow(x, -1, Q), -1, Q) % Q
         for x in points]
    v = propagation()
    verify_network(v)
    print("production network propagation verified", flush=True)
    alpha, sizes = construct(v, a)
    b, beta = transpose(a), transpose(alpha)
    assert b == [1] * N
    aa, al = ([row[bitrev8(i)] for i in range(N)] for row in (a, alpha))
    first, second = pullback(aa), pullback(al)
    assert first[:N] == b and second[:N] == beta
    for r, row in enumerate(v):
        assert first[r] == sum(a[j] * c for j, c in row.items()) % Q
        assert second[r] == sum(alpha[j] * c for j, c in row.items()) % Q
    zero = sum((first[r] * second[s] - first[s] * second[r]) % Q == 0
               for r in range(len(v)) for s in range(r))
    assert zero == 0, zero
    raw = b''.join(x.to_bytes(4, 'little') for row in (b, aa, beta, al) for x in row)
    content = "// generated by tools/gen_prior_checker.py\n\n"
    content += "\n\n".join((render('prior_a', aa), render('prior_beta', beta),
                              render('prior_alpha', al[::2]))) + "\n"
    cert = {
        "paper": "https://eprint.iacr.org/2025/170",
        "sections": ["3.1", "3.2", "3.3 Theorems 4 and 5", "4.1", "4.2"],
        "n": N, "q": Q, "h": H,
        "modeled_locations": len(v),
        "checked_pairs": len(v) * (len(v) - 1) // 2,
        "zero_first_responses": first.count(0),
        "zero_second_responses": second.count(0),
        "zero_determinants": zero,
        "row_identities": "direct evaluation and network pullback passed",
        "propagation_identity": "all unit wires matched the production network",
        "coefficients_sha256": hashlib.sha256(raw).hexdigest(),
        "digest_format": "b then a then beta then alpha in production order as uint32 little endian",
        "network_sha256": hashlib.sha256(json.dumps(layers(), separators=(',', ':')).encode()).hexdigest(),
        "stored_coefficients": N + N + N // 2,
        "stored_bytes": 4 * (N + N + N // 2),
        "largest_forbidden_set": max(sizes),
        "tie_break": "smallest legal field value in descending natural output index order",
        "fixed_natural_alpha_indices": [128, 255],
    }
    assert all(al[i] == 1 for i in range(1, N, 2))
    return content, json.dumps(cert, indent=2) + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    content, cert = generate()
    if args.check:
        assert OUT.read_text() == content, 'checker constants differ'
        assert CERT.read_text() == cert, 'checker certificate differs'
    else:
        OUT.write_text(content)
        CERT.write_text(cert)
    print(cert, end='')


if __name__ == '__main__':
    main()
