#!/usr/bin/env python3
import argparse
import ctypes as C
import hashlib
import json
from pathlib import Path

Q = 8380417
N = 256
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "platform/cortexm4/mps2_vectors.inc"


def arr(name, data):
    out = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join(f"0x{x:02x}" for x in data[i:i + 16]) + ",")
    out.append("};")
    return "\n".join(out)


def digest_words(a):
    raw = b"".join(x.to_bytes(4, "little") for x in a)
    return hashlib.shake_256(raw).digest(32)


def bitrev(x):
    return int(f"{x:08b}"[::-1], 2)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    root = ROOT / "build/nist/ML-DSA-keyGen-FIPS204"
    prompts = json.loads((root / "prompt.json").read_text())
    answers = json.loads((root / "expectedResults.json").read_text())
    group = prompts["testGroups"][0]
    case = group["tests"][0]
    answer = answers["testGroups"][0]["tests"][0]
    assert group["parameterSet"] == "ML-DSA-44"
    assert case["tcId"] == answer["tcId"]
    seed = bytes.fromhex(case["seed"])
    pk = bytes.fromhex(answer["pk"])
    sk = bytes.fromhex(answer["sk"])
    lib = C.CDLL(str((ROOT / "build/libmldsa.so").resolve()))
    lib.mldsa44_sign.argtypes = [C.c_void_p, C.c_void_p, C.c_size_t,
                                 C.c_void_p, C.c_size_t, C.c_void_p,
                                 C.c_size_t, C.c_void_p]
    lib.mldsa44_sign.restype = C.c_int
    msg = b"Cortex M4 portable baseline"
    ctx = b"arm"
    rnd = bytes(range(32))
    sig = C.create_string_buffer(2420)
    assert lib.mldsa44_sign(sig, sk, len(sk), msg, len(msg), ctx, len(ctx), rnd) == 0

    polys = [[0] * N, [0, 1] + [0] * (N - 2),
             [Q - 1 if i % 2 else 0 for i in range(N)]]
    a = []
    x = 20446
    for _ in range(N):
        x = (1664525 * x + 1013904223) % (1 << 32)
        a.append(x % Q)
    polys.append(a)
    assert pow(1753, N, Q) == Q - 1
    points = [pow(1753, 2 * bitrev(i) + 1, Q) for i in range(N)]
    ntt = [digest_words([sum(a[j] * pow(x, j, Q) for j in range(N)) % Q
                         for x in points]) for a in polys]

    root = ROOT / "build/nist/SHAKE-256-FIPS202"
    prompts = json.loads((root / "prompt.json").read_text())
    answers = json.loads((root / "expectedResults.json").read_text())
    case = next(t for g in prompts["testGroups"] for t in g["tests"]
                if t["tcId"] == 188)
    answer = next(t for g in answers["testGroups"] for t in g["tests"]
                  if t["tcId"] == case["tcId"])
    assert case["len"] == 168 and case["outLen"] == 256
    shake_msg = bytes.fromhex(case["msg"])
    shake = bytes.fromhex(answer["md"])
    assert hashlib.shake_256(shake_msg).digest(len(shake)) == shake

    values = (
        ("kat_seed", seed),
        ("kat_pk", hashlib.shake_256(pk).digest(32)),
        ("kat_sk", hashlib.shake_256(sk).digest(32)),
        ("kat_sig", hashlib.shake_256(sig.raw).digest(32)),
        ("kat_ntt_zero", ntt[0]),
        ("kat_ntt_basis", ntt[1]),
        ("kat_ntt_boundary", ntt[2]),
        ("kat_ntt_random", ntt[3]),
        ("kat_shake_msg", shake_msg),
        ("kat_shake", shake),
    )
    content = "// generated by tools/gen_arm_vectors.py\n" + "\n\n".join(arr(*v) for v in values) + "\n"
    if args.check:
        if OUT.read_text() != content:
            raise SystemExit("ARM vectors differ from generator output")
        print("ARM vectors verified")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(content)
        print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
