#!/usr/bin/env python3
import hashlib
import json
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(args):
    return subprocess.check_output(args, cwd=ROOT, text=True)


def main():
    size = os.environ.get('ARM_SIZE', 'arm-none-eabi-size')
    cc = os.environ.get('ARM_CC', 'arm-none-eabi-gcc')
    counts = json.loads(run(['build/count_checkers']))
    assert counts['baseline'] == {'mul': 1024, 'add': 1024, 'sub': 1024}
    variants = {}
    for name in ('baseline', 'prior', 'our'):
        suffix = '' if name == 'baseline' else '_' + name
        elf = ROOT / f'build/arm/mps2{suffix}_bench.elf'
        usage = run([size, str(elf)]).splitlines()[1].split()
        image = dict(zip(('text', 'data', 'bss'), map(int, usage[:3])))
        record = '' if name == 'baseline' else '-' + name
        path = f'test/qemu-mps2-an386{record}.json'
        qemu = json.loads((ROOT / path).read_text())
        assert qemu['cases'] and all(x.endswith('PASS') for x in qemu['cases'])
        extra = {key: counts[name][key] - counts['baseline'][key] for key in counts[name]}
        data = {
            'checks': 0 if name == 'baseline' else 2,
            'stored_coefficients': 0, 'constant_bytes': 0,
            'field_calls': counts[name], 'extra_field_calls': extra,
            'arm_image': image,
            'elf_sha256': hashlib.sha256(elf.read_bytes()).hexdigest(),
            'qemu': {'status': 'passed', 'target': qemu['target'],
                     'emulator': qemu['emulator'], 'record': path},
        }
        if name != 'baseline':
            cert = json.loads((ROOT / f'docs/{name}_certificate.json').read_text())
            arrays = re.findall(r'static const uint32_t \w+\[(\d+)\]',
                                (ROOT / f'src/{name}_tables.inc').read_text())
            coeffs = sum(map(int, arrays))
            assert coeffs == cert['stored_coefficients']
            data.update(stored_coefficients=coeffs, constant_bytes=4 * coeffs,
                        coefficients_sha256=cert['coefficients_sha256'])
        variants[name] = data
    assert variants['prior']['extra_field_calls'] == {'mul': 640, 'add': 1024, 'sub': 0}
    assert variants['our']['extra_field_calls'] == {'mul': 768, 'add': 1024, 'sub': 0}
    data = {
        'purpose': 'field operation counts and linked emulator image sizes only',
        'compiler': run([cc, '--version']).splitlines()[0],
        'architecture': '-mcpu=cortex-m4 -mthumb -mfloat-abi=soft',
        'optimization': '-O2', 'linker': 'platform/cortexm4/mps2.ld',
        'variants': variants,
        'physical_cycles': 'pending', 'physical_flash_ram_stack': 'pending',
    }
    dst = ROOT / 'bench/checker_costs.json'
    dst.parent.mkdir(exist_ok=True)
    dst.write_text(json.dumps(data, indent=2) + '\n')
    lines = ['# NTT checker provisional comparison', '',
             'Generated by `python3 tools/measure_checkers.py` from [raw results](../bench/checker_costs.json).', '',
             '| Variant | Checks | Stored coefficients | Extra field mul | Extra field add | Constant bytes | ARM text | ARM data | ARM BSS | QEMU correctness |',
             '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |']
    labels = {'baseline': 'Baseline', 'prior': 'Abdelmonem two checks', 'our': 'Our deterministic two checks'}
    for name, row in variants.items():
        values = [row['checks'], row['stored_coefficients'], row['extra_field_calls']['mul'],
                  row['extra_field_calls']['add'], row['constant_bytes']]
        values += [row['arm_image'][key] for key in ('text', 'data', 'bss')]
        lines.append('| ' + labels[name] + ' | ' + ' | '.join(map(str, values)) + ' | Passed |')
    lines += ['',
              'Counts are additions and multiplications beyond one baseline forward NTT. There are no additional modular subtractions. Baseline itself calls each field operation 1024 times. The counter wraps the actual modular function bodies using a fixed nonzero benchmark polynomial.', '',
              'The prior checker stores 640 coefficients and omits products for its 128 implicit unity output weights. Our straightforward implementation stores all 768 weighted coefficients and performs all products. Both accumulate four 256 term checks. The construction improves the sufficient field bound; these measurements show 128 more products and 512 more constant bytes for our current execution implementation.', '',
              'ARM text includes readonly constants and the vector table. All three images use the same compiler, flags, linker, input, and benchmark harness, without test injection hooks. ELF digests are recorded in the raw results. Image sizes describe the emulator layout. Physical flash, RAM, stack, and DWT cycles remain pending. QEMU supplied correctness checks only.', '']
    (ROOT / 'docs/checker_costs.md').write_text('\n'.join(lines))
    print(json.dumps(data, indent=2))


if __name__ == '__main__':
    main()
