#!/usr/bin/env python3
import json
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(args):
    return subprocess.check_output(args, cwd=ROOT, text=True)


def main():
    size = os.environ.get('ARM_SIZE', 'arm-none-eabi-size')
    cc = os.environ.get('ARM_CC', 'arm-none-eabi-gcc')
    counts = json.loads(run(['build/count_prior']))
    assert counts['extra'] == {'mul': 640, 'add': 1024, 'sub': 0}
    cert = json.loads((ROOT / 'docs/prior_certificate.json').read_text())
    arrays = re.findall(r'static const uint32_t \w+\[(\d+)\]',
                        (ROOT / 'src/prior_tables.inc').read_text())
    coeffs = sum(map(int, arrays))
    assert coeffs == cert['stored_coefficients']
    images = {}
    for name, file in (('baseline', 'mps2_bench.elf'), ('prior', 'mps2_prior_bench.elf')):
        usage = run([size, f'build/arm/{file}']).splitlines()[1].split()
        images[name] = dict(zip(('text', 'data', 'bss'), map(int, usage[:3])))
    qemu = json.loads((ROOT / 'test/qemu-mps2-an386-prior.json').read_text())
    assert all(x.endswith('PASS') for x in qemu['cases'])
    data = {
        'purpose': 'field operation counts and linked emulator image sizes only',
        'compiler': run([cc, '--version']).splitlines()[0],
        'architecture': '-mcpu=cortex-m4 -mthumb -mfloat-abi=soft',
        'optimization': '-O2',
        'linker': 'platform/cortexm4/mps2.ld',
        'field_calls': counts,
        'prior_checks': 2,
        'prior_stored_coefficients': coeffs,
        'prior_constant_bytes': 4 * coeffs,
        'coefficients_sha256': cert['coefficients_sha256'],
        'arm_images': images,
        'arm_size_change': {k: images['prior'][k] - images['baseline'][k]
                            for k in ('text', 'data', 'bss')},
        'qemu': {'target': qemu['target'], 'status': 'passed',
                 'emulator': qemu['emulator'],
                 'record': 'test/qemu-mps2-an386-prior.json'},
        'physical_cycles': 'pending',
        'physical_flash_ram_stack': 'pending',
    }
    dst = ROOT / 'bench/prior_costs.json'
    dst.parent.mkdir(exist_ok=True)
    dst.write_text(json.dumps(data, indent=2) + '\n')
    lines = ['# Prior checker provisional costs', '',
             'Generated by `python3 tools/measure_prior.py` from [raw results](../bench/prior_costs.json).', '',
             '| Variant | Checks | Coefficients | Extra field mul | Extra field add | Constant bytes | ARM text | ARM data | ARM BSS |',
             '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |']
    for name in ('baseline', 'prior'):
        image = images[name]
        fields = [0] * 5 if name == 'baseline' else [
            2, coeffs, counts['extra']['mul'], counts['extra']['add'], 4 * coeffs]
        fields += [image[k] for k in ('text', 'data', 'bss')]
        lines.append('| ' + name + ' | ' + ' | '.join(map(str, fields)) + ' |')
    lines += ['', 'ARM text includes readonly tables and the vector table. These are matched benchmark ELF images with no fault injection hooks; their emulator memory layout is not a physical flash/RAM measurement.', '',
              'The host counter measures calls to the actual modular functions for one forward transform. There are no additional modular subtractions. Both variants use the same polynomial representation and benchmark inputs.', '',
              'QEMU compact correctness: passed. Physical cycle, flash, RAM, and stack measurements: pending.', '']
    (ROOT / 'docs/prior_costs.md').write_text('\n'.join(lines))
    print(json.dumps(data, indent=2))


if __name__ == '__main__':
    main()
